##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



In [1]:
import numpy as np

#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [2]:
## write code here
print(np.__version__)

1.23.5


#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [3]:
## write code here
d=np.arange(1,17)

In [4]:
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [5]:
d[d%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [6]:
## write code here
f=np.arange(1,17,2)

In [7]:
print(f)

[ 1  3  5  7  9 11 13 15]


#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [8]:
## write code here
y=np.arange(1,17)
y[y%2==1]=0


In [9]:
print(y)

[ 0  2  0  4  0  6  0  8  0 10  0 12  0 14  0 16]


#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

In [10]:
## write code here
p=y.reshape(4,4)

In [11]:
p

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [12]:
## write code here
j=np.vstack((p,p))

In [13]:
j

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16],
       [ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [14]:
## write code here


In [15]:
new=j[:,[1,0,3,2]]
print(new)

[[ 2  0  4  0]
 [ 6  0  8  0]
 [10  0 12  0]
 [14  0 16  0]
 [ 2  0  4  0]
 [ 6  0  8  0]
 [10  0 12  0]
 [14  0 16  0]]


#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [16]:
new

array([[ 2,  0,  4,  0],
       [ 6,  0,  8,  0],
       [10,  0, 12,  0],
       [14,  0, 16,  0],
       [ 2,  0,  4,  0],
       [ 6,  0,  8,  0],
       [10,  0, 12,  0],
       [14,  0, 16,  0]])

In [17]:
## write code here
mean=np.mean(new)
median=np.median(new)

In [18]:
mean

4.5

In [19]:
median

1.0

In [20]:
import statistics

In [21]:
_,idx, count = np.unique(new.reshape(32, ),return_index=True ,return_counts=True)

In [22]:
index =idx[np.argmax(count)]

In [23]:
MODEE=new.reshape(32,)[index]

In [24]:
new

array([[ 2,  0,  4,  0],
       [ 6,  0,  8,  0],
       [10,  0, 12,  0],
       [14,  0, 16,  0],
       [ 2,  0,  4,  0],
       [ 6,  0,  8,  0],
       [10,  0, 12,  0],
       [14,  0, 16,  0]])

In [25]:
MODEE

0

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

In [38]:
j

array([[ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16],
       [ 0,  2,  0,  4],
       [ 0,  6,  0,  8],
       [ 0, 10,  0, 12],
       [ 0, 14,  0, 16]])

In [41]:
## write code here



In [39]:
ramdom_arr = np.array([np.random.choice(j.reshape(32,)) for i in range(5)])

In [40]:
ramdom_arr

array([0, 0, 2, 0, 0])

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [32]:
def BCE(y, y_hat):
    return (y*np.log(y_hat)- (1-y)*np.log(1-y_hat)).mean()
    ## write code here
    

In [33]:
y = np.array([0.13,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.1])
y_hat = np.array([0.2,0.3,0.4,0.3,0.6,0.8,0.7,0.5,0.8,0.1])

result = BCE(y, y_hat)
print(result)

0.007749312731669802
